# Generated by Django 2.1.1 on 2019-01-23 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('date_of_birth', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=200)),
                ('school_10th', models.CharField(max_length=100)),
                ('percentage_10th', models.IntegerField()),
                ('school_12th', models.CharField(max_length=100)),
                ('percentage_12th', models.IntegerField()),
                ('graduation', models.CharField(choices=[('B.tech', 'B.tech'), ('B.sc', 'B.sc'), ('BCA', 'BCA'), ('MCA', 'MCA'), ('BBA', 'BBA'), ('B.E', 'B.E'), ('None', 'None')], max_length=7)),
                ('branch_graduation', models.CharField(choices=[('Computer science', 'Computer science'), ('Information technology', 'Information technology'), ('Computer engineering', 'Computer engineering'), ('Mathematics', 'Mathematics'), ('Machine learning', 'Machine learning'), ('Electronics and communication', 'Electronics and communication'), ('None', 'None')], max_length=30)),
                ('technical_skills_and_language', models.CharField(choices=[('C++', 'C++'), ('C', 'C'), ('JAVA', 'JAVA'), ('C#', 'C#'), ('.NET', '.NET'), ('PYTHON', 'PYTHON'), ('JavaScript', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Database', 'Database'), ('Networking', 'Networking'), ('Cloud', 'Cloud'), ('Android', 'Android'), ('Machine learning', 'ML'), ('AI', 'AI'), ('Data science', 'Data science')], max_length=15)),
                ('Other_skills', models.CharField(blank=True, choices=[('C++', 'C++'), ('C', 'C'), ('JAVA', 'JAVA'), ('C#', 'C#'), ('.NET', '.NET'), ('PYTHON', 'PYTHON'), ('JavaScript', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Database', 'Database'), ('Networking', 'Networking'), ('Cloud', 'Cloud'), ('Android', 'Android'), ('Machine learning', 'ML'), ('AI', 'AI'), ('Data science', 'Data science')], max_length=15)),
                ('Main_Hobbies', models.CharField(choices=[('Reading books', 'Reading books'), ('reading novels', 'reading novels'), ('Cooking', 'Cooking'), ('Watching Movies', 'Watching Movies'), ('Playing Badminton', 'Playing Badminton'), ('Playing Cricket', 'Playing Cricket'), ('Playing football', 'Playing football'), ('Playing basketball', 'Playing basketball'), ('Playing Chess', 'Playing Chess'), ('Going Gym', 'Going Gym'), ('listening Music', 'listening Music'), ('Dancing', 'Dancing')], max_length=25)),
                ('Other_Hobbies', models.CharField(blank=True, choices=[('Reading books', 'Reading books'), ('reading novels', 'reading novels'), ('Cooking', 'Cooking'), ('Watching Movies', 'Watching Movies'), ('Playing Badminton', 'Playing Badminton'), ('Playing Cricket', 'Playing Cricket'), ('Playing football', 'Playing football'), ('Playing basketball', 'Playing basketball'), ('Playing Chess', 'Playing Chess'), ('Going Gym', 'Going Gym'), ('listening Music', 'listening Music'), ('Dancing', 'Dancing')], max_length=25)),
                ('achievement', models.CharField(blank=True, max_length=100)),
                ('Project_Done', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
