# Generated by Django 2.1.7 on 2019-03-08 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Front', '0003_auto_20190305_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='result_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('date_of_exam', models.DateTimeField(auto_now_add=True)),
                ('exam_name', models.CharField(max_length=256)),
                ('user_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='Category',
            field=models.CharField(choices=[('Concept', 'Concept'), ('HR', 'HR'), ('TECHNICAL', 'TECHNICAL'), ('GK', 'GK'), ('Reading books', 'Reading books'), ('reading novels', 'reading novels'), ('Cooking', 'Cooking'), ('Watching Movies', 'Watching Movies'), ('Playing Badminton', 'Playing Badminton'), ('Playing Cricket', 'Playing Cricket'), ('Playing football', 'Playing football'), ('Playing basketball', 'Playing basketball'), ('Playing Chess', 'Playing Chess'), ('Going Gym', 'Going Gym'), ('listening Music', 'listening Music'), ('Dancing', 'Dancing'), ('C++', 'C++'), ('C', 'C'), ('JAVA', 'JAVA'), ('C#', 'C#'), ('.NET', '.NET'), ('PYTHON', 'PYTHON'), ('JavaScript', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Database', 'Database'), ('Networking', 'Networking'), ('Cloud', 'Cloud'), ('Android', 'Android'), ('Machine learning', 'ML'), ('AI', 'AI'), ('Data science', 'Data science')], max_length=50),
        ),
    ]
