# Generated by Django 2.1.7 on 2019-03-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0004_auto_20190308_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_marks', models.PositiveSmallIntegerField()),
                ('cm_position', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='company_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=256)),
                ('Position', models.CharField(max_length=256)),
                ('Difficulty_level', models.PositiveIntegerField()),
                ('salary_in_rupees', models.PositiveIntegerField()),
                ('min_experience_in_years', models.PositiveIntegerField()),
                ('Discreption', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='company_marks',
            name='Company_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Front.company_post'),
        ),
        migrations.AddField(
            model_name='company_marks',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Front.result_user'),
        ),
    ]
