# Generated by Django 2.1.7 on 2019-03-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0005_auto_20190318_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_marks',
            name='Company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Front.company_post'),
        ),
    ]
